### ISSUE TITLE
Error in dir_copy(file.path(cacheLibDir(pkgRecord$name, pkgRecord$hash)), 

### ISSUE THREAD

**Issue by pgensler** [rstudio/packrat#322]
When I try to use Packrat with RStudio 0.99.1285, I have an issue where I have loaded a package that Packrat thinks needs to be updated into my library (and is in my lock file), but when I try to install it back into my workspace, I get the following error:
Installing manipulate (1.0.1) ... 
Error in dir_copy(file.path(cacheLibDir(pkgRecord$name, pkgRecord$hash)),  : 
  Directory already exists at path '/Users/petergensler/Desktop/SuperStore Analysis/packrat/lib/x86_64-apple-darwin13.4.0/3.3.1/manipulate'. 

I don't think packrat is fully restoring all of the packages from my lock file. Attached is my session info, and the lock file. Let me know how I can help.

R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.6 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] magrittr_1.5    formatR_1.4     htmltools_0.3.5 tools_3.3.1     yaml_2.1.13    
 [6] Rcpp_0.12.5     stringi_1.1.1   rmarkdown_1.0   knitr_1.14      stringr_1.0.0  
[11] digest_0.6.9    packrat_0.4.7-1 evaluate_0.9

**Comment by kevinushey** [comment]
Does this issue reproduce if you use the development version of packrat? Try `devtools::install_github('rstudio/packrat') to install.

**Comment by pgensler** [comment]
Kevin, I'm not sure. I posted a thread on the packrat google group with a little more detail on some of the issues I've been experiencing.

**Comment by pgensler** [comment]
Ok, so I tried installing the dev version of packrat, and I get this error.....
Downloading GitHub repo rstudio/packrat@master
from URL https://api.github.com/repos/rstudio/packrat/zipball/master
Installing packrat
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/c9/4v_941557p15th5c9lkxnysr0000gn/T/Rtmpa49snh/devtools27a423fd71a1/rstudio-packrat-d2a3e31'  \
  --library='/Users/petergensler/Desktop/SuperStore  \
  Analysis/packrat/lib/x86_64-apple-darwin13.4.0/3.3.1' --install-tests 

ERROR: ‘packrat’ is not a legal package name
Error: Command failed (1)

**Comment by kevinushey** [comment]
That particular bizarre error is now resolved in the development versions of R -- it's basically a bad interaction between R + the packrat cache, as R's install / remove package functions don't work well when the packages in an R library are symlinks instead of plain directories.

To work around it, you'll need to explicitly remove the `packrat` package and then try to reinstall it, e.g.

```
remove.packages("packrat")
devtools::install_github("rstudio/packrat")
```

**Comment by kevinushey** [comment]
We also had another separate report re: XQuartz automatically launching when RStudio starts up, but don't know what's going on there yet. Does this occur only within packrat projects, or does it occur in other projects in the IDE?

The closest related issue that we've seen is with loading of the `colorspace` package, e.g. http://stackoverflow.com/questions/28952128/loading-ggplot2-colorspace-actually-opens-up-x11.

**Comment by pgensler** [comment]
When I try to use a different project, I think packrat seems to work fine(CRAN 0.4.7-1). However, I still get two Packrat Libraries appearing, and the first one does not seem to list where my packages are coming from. Some that are installed from github(like plotly) do not list they are from Github. I have attached a few screenshots to help illustrate.
![double-packratlib](https://cloud.githubusercontent.com/assets/7308115/17674344/c25d2ef4-62ea-11e6-9a6a-17322ba99146.png)
![no-github](https://cloud.githubusercontent.com/assets/7308115/17674343/c25b4328-62ea-11e6-83e1-32626e392b84.png)

**Comment by pgensler** [comment]
Do you want me to test the Dev version of packrat with a new RStudio Project, as I've only used the CRAN version so far?

**Comment by kevinushey** [comment]
One possibility is that these packages are detected as dependencies in your project -- for example, they're required by other packages currently installed / in use in your project; or you're explicitly loading them in a script file somewhere.

Can you check what the output of the following is:

```
packrat:::appDependencies()
packrat:::status()
```

My guess is that the packages `lubridate`, `stringi` and `stringr` might be reported on in each case.

**Comment by pgensler** [comment]
Well here is a cryptic response from those commands:........ packrat:::appDependencies()
  [1] "BH"            "DBI"           "DT"            "GREA"          "NMF"          
  [6] "R.matlab"      "R.methodsS3"   "R.oo"          "R.utils"       "R6"           
 [11] "RColorBrewer"  "RODBC"         "RSQLite"       "Rcpp"          "XLConnect"    
 [16] "XLConnectJars" "XML"           "assertthat"    "base64enc"     "bitops"       
 [21] "brew"          "caTools"       "cellranger"    "chron"         "colorspace"   
 [26] "csvy"          "curl"          "data.table"    "devtools"      "dichromat"    
 [31] "digest"        "doParallel"    "dplyr"         "evaluate"      "foreach"      
 [36] "foreign"       "formatR"       "formattable"   "ggplot2"       "ggthemes"     
 [41] "ggvis"         "git2r"         "gridBase"      "gridExtra"     "gsubfn"       
 [46] "gtable"        "haven"         "hexbin"        "highr"         "hms"          
 [51] "htmltools"     "htmlwidgets"   "httpuv"        "httr"          "igraph"       
 [56] "irlba"         "iterators"     "jsonlite"      "knitr"         "labeling"     
 [61] "lazyeval"      "lubridate"     "magrittr"      "manipulate"    "markdown"     
 [66] "memoise"       "mime"          "miniCRAN"      "miniUI"        "munsell"      
 [71] "openssl"       "openxlsx"      "packrat"       "pkgmaker"      "plotly"       
 [76] "plyr"          "prettydoc"     "printr"        "proto"         "purrr"        
 [81] "rJava"         "readODS"       "readr"         "readxl"        "registry"     
 [86] "reshape2"      "rhandsontable" "rio"           "rmarkdown"     "rngtools"     
 [91] "roxygen2"      "rpivotTable"   "rstudioapi"    "scales"        "shiny"        
 [96] "slidify"       "sqldf"         "stattleshipR"  "stringi"       "stringr"      
[101] "tibble"        "tidyr"         "triebeard"     "urltools"      "viridis"      
[106] "webshot"       "whisker"       "withr"         "xml2"          "xtable"       
[111] "yaml"         
Warning messages:
1: In readLines(file) :
  incomplete final line found on '/Users/petergensler/Desktop/SuperStore Analysis/Untitled.Rmd'
2: In FUN(X[[i]], ...) :
  Package 'printr' not available in repository or locally
> packrat:::status()

The following packages are tracked by packrat, but are no longer available in the local library nor present in your code:
                     _      
    slidifyLibraries   0.3.1

You can call packrat::snapshot() to remove these packages from the lockfile, or if you intend to use these packages, use packrat::restore() to restore them to your private library.

The following packages are referenced in your code, but are not present
in your library nor in packrat:

    brew
    printr
    roxygen2

You will need to install these packages manually, then use
packrat::snapshot() to record these packages in packrat.
Error in if (pkg$name == pkgName) return(pkg) : 
  argument is of length zero
In addition: Warning messages:
1: In FUN(X[[i]], ...) : No DESCRIPTION file for installed package 'GREA'
2: In readLines(file) :
  incomplete final line found on '/Users/petergensler/Desktop/SuperStore Analysis/Untitled.Rmd'
3: In FUN(X[[i]], ...) :
  Package 'printr' not available in repository or locally

**Comment by kevinushey** [comment]
Right -- okay, `packrat` is detecting that the packages `brew`, `stringi` and `stringr` are dependencies of your project, but are currently not installed / not tracked by `packrat`.

RStudio sees this, but still displays these packages as entries in the Packages pane -- unfortunately, the experience here is quite confusing.

The errors in `status()` are unrelated, although I should make sure to clean those up soon.

**Comment by pgensler** [comment]
That, and if I try to add or make changes to those packages, I really can't do anything. Do you want my lock file to look at?

**Comment by kevinushey** [comment]
It might be worth posting for posterity. The `manipulate` error posted in the first comment is likely due to the use of the packrat cache, so I'm hopeful that this is fixed in the development version of packrat.

Otherwise, you might need to explicitly remove the package with e.g. `remove.packages("manipulate")`.

**Comment by pgensler** [comment]
Attaching the .lock file. One future feature to think about with Packrat is having the ability to "reset" your workspace to the default packages. I've found myself installing packages so many times, but having issues like this with uninstalling manipulate. Maybe like a docker container environment to test out a package to see how it works?

When I try to remove the manipulate package, it looks like it has been removed, but packrat does not detech that. 
[packrat.lock.txt](https://github.com/rstudio/packrat/files/418696/packrat.lock.txt)


![remove-manipulate-package](https://cloud.githubusercontent.com/assets/7308115/17674943/4c9732ac-62ed-11e6-821a-543fe2106f8b.png)

**Comment by kevinushey** [comment]
After removing the package, you need to either `snapshot()` to 'save the state' of your library; or, if the `manipulate` package is actually required by your project, then the UI will prompt you to install the package (as it's doing here).

**Comment by pgensler** [comment]
OK, so I am trying to remove the manipulate package and printr, but when I try to snapshot my library, I get the following error:
packrat::snapshot()
Error: Unable to retrieve package records for the following packages:
- 'GREA'
In addition: Warning messages:
1: In readLines(file) :
  incomplete final line found on '/Users/petergensler/Desktop/SuperStore Analysis/Untitled.Rmd'
2: In FUN(X[[i]], ...) :
  Package 'printr' not available in repository or locally

**Comment by kevinushey** [comment]
How were the packages `GREA` and `printr` installed? You likely need to make sure they were installed from CRAN / GitHub; otherwise, you might need to add them to the set of ignored packages with e.g.

```
packrat::opts$ignored.packages(c("GREA", "printr"))
```

**Comment by pgensler** [comment]
They were both installed with install_github.
