### ISSUE TITLE
Can't activate packrat if no in the packrat project

### ISSUE THREAD

**Issue by cderv** [rstudio/packrat#496]
`packrat::on()` has a `project` argument that should allow to activate a project from another working directory. My use case to find this error is using packrat with docker and shiny server.

When I am in let's say the user home and I want to activate packrat with `packrat::on()` after unbundling, I run 
```bash
Rscript -e "packrat::on('/srv/shiny-server/app_folder')" 
```
I get this error message 
```
Error in read.dcf(...) : cannot open the connection
Calls: <Anonymous> ... getPackageDependencies -> readLockFilePackages -> readDcf -> read.dcf
In addition: Warning message:
In read.dcf(...) :
  cannot open compressed file '//packrat/packrat.lock', probable reason 'No such file or directory'
Execution halted
```

This is because somewhere  `getPackageDependencies` is called without any project argument and `readLockFilePackages(file = lockFilePath())` is run searching for `packrat.lock` in the current working directory.

Before investigating further, is this an intended use of the `project` argument from `packrat::on` ? 

Thanks.

**Comment by kevinushey** [comment]
I think this should work; the fact that it doesn't means this is a bug in Packrat.

As a workaround, would it be reasonable to move into the requested directory, call `packrat::on()`, and then move home? E.g.

```R
Rscript -e "setwd(dir); packrat::on()"
```

**Comment by cderv** [comment]
I came up with this 
``` r
# dir for project
dir_proj <- tempfile("packrat-proj")
dir.create(dir_proj)
# init packrat
setwd(dir_proj)
packrat::init(enter = FALSE)
#> Initializing packrat project in directory:
#> - "C:/Users/chris/AppData/Local/Temp/RtmpqIupB2/packrat-proj32944fc7471c"
#> 
#> Adding these packages to packrat:
#>             _        
#>     packrat   0.4.9-3
#> Fetching sources for packrat (0.4.9-3) ...
#> OK (CRAN current)
#> Snapshot written to "C:/Users/chris/AppData/Local/Temp/RtmpqIupB2/packrat-proj32944fc7471c/packrat/packrat.lock"
#> Installing packrat (0.4.9-3) ...
#>  OK (downloaded binary)
#> Initialization complete!
.libPaths()
#> [1] "C:/Users/chris/Documents/R/win-library/3.5"
#> [2] "C:/Program Files/R/R-3.5.1/library"
# change directory
dir.create(other_dir <- tempfile("other-dir"))
setwd(other_dir)
# try packrat::on from this other dir
callr::r(function(dir_proj) {
  packrat::on(project = dir_proj)
  .libPaths()
} ,args = list(dir_proj = dir_proj), 
show = TRUE)
#> Error in read.dcf(...) : impossible d'ouvrir la connexion
#> Calls: withCallingHandlers ... readLockFilePackages -> readDcf -> read.dcf -> .handleSimpleError -> h
#> De plus : Warning message:
#> In read.dcf(...) :
#>   impossible d'ouvrir le fichier compressé 'C:/Users/chris/AppData/Local/Temp/RtmpqIupB2/other-dir3294349c34bc/packrat/packrat.lock', cause probable : 'No such file or directory'
#> Exécution arrêtée
#> Error in read.dcf(...): impossible d'ouvrir la connexion
```
The packrat.lock is not read from the project dir given to `on()` but looked into the current working directory where the command is launched.

<details><summary>And also, reproduced with this Dockerfile, where last step give an error when `docker build`</summary>

```dockerfile
FROM rocker/r-ver:latest
RUN install2.r packrat
WORKDIR ~
RUN mkdir -p pkproj
RUN r -e 'packrat::init("pkproj", enter = FALSE)'
# this gives an error
RUN r -e 'packrat::on("pkproj")'
````
</details>

**Comment by cderv** [comment]
The issue is here 
https://github.com/rstudio/packrat/blob/40b8f5b3b1b1d47daaf182ca33935249d3517637/R/library-support.R#L133-L137
that calls `getPackageDependencies ` that looks for the lockfile if packrat mode is on, but without any project argument so, inside the current working dir
https://github.com/rstudio/packrat/blob/653bded75c4e058271810e7f04012225b6553581/R/recursive-package-dependencies.R#L6-L8

This is where the error comes from. We may need to pass the project arg, unless information of packrat project dir is availiable somewhere of packrat mode is on. But I am not sure an environment variable is set to store the value... 
I let you see this before proposing any fix with a PR. You may know better than me how to deal with this

**Comment by kevinushey** [comment]
Indeed, most functions in Packrat that require information about the project accept an argument `project`, with a default value of `NULL`, and normalize to the 'current' project. E.g. this pattern is common:

```R
packratFunction <- function(project = NULL) {
    project <- getProjectDir(project)
    ...
}
```

For fixing this, perhaps just reading the project directory explicitly with `getProjectDir()` would be a better fix than trying to thread the new `project` argument around.

**Comment by cderv** [comment]
> For fixing this, perhaps just reading the project directory explicitly with getProjectDir() would be a better fix than trying to thread the new project argument around.

Yes I think so. It is the easiest and less impacting solution. However, I wonder if other functions in the process are lacking this project information to work properly also in this case. 🤔 If so, it would be interesting to pass around the project argument

**Comment by markusdumke** [comment]
I think I have the same problem using packrat with docker and shiny server. I tried the suggested workaround but get an error.

This is the relevant part of my docker file:
```
COPY app.R /srv/shiny-server/
COPY packrat/packrat.* /srv/shiny-server/packrat/
RUN R -e 'install.packages("packrat", repos = "https://cran.rstudio.com/")'
RUN R -e 'packrat::restore(project = "/srv/shiny-server");'
RUN R -e 'setwd("srv/shiny-server"); packrat::on()'
```

The last command returns the following error:

```
Error in !packrat::opts$symlink.system.packages() : invalid argument type
Calls: <Anonymous> ... setPackratModeOn -> afterPackratModeOn -> symlinkSystemPackages
Execution halted
```

Any ideas how to fix this?

**Comment by markusdumke** [comment]
@cderv I tried adding a slash in front of srv, but it does not make a difference, the error message is the same.

**Comment by kevinushey** [comment]
Does your project have a file at `packrat/packrat.opts`? If so, what is its contents?

What is the output of running `packrat::opts$symlink.system.packages()`?

I suspect the value is somehow `NULL` in your case.

**Comment by markusdumke** [comment]
I put the code online at https://gitlab.com/markusdumke/test_app

`packrat::opts$symlink.system.packages()` returns `Error: attempt to apply non-function`

**Comment by kevinushey** [comment]
Are you using an older version of Packrat? That seems surprising to me.

**Comment by markusdumke** [comment]
0.4.9-3

**Comment by markusdumke** [comment]
I have reinstalled packrat 0.5.0, ran`packrat::init` and `packrat::snapshot `and that have fixed it: https://gitlab.com/markusdumke/test_app/commit/8395b98d79070b7c64903fd26e75fb3e60294a03

**Comment by cderv** [comment]
The issue you mentioned [above](https://github.com/markusdumke) was with `symlink.system.packages` which was introduced in [0.5.0](https://github.com/rstudio/packrat/blob/master/NEWS.md#packrat-050). 
This could explain why reinstalling fixed your issue. The one I described still remains.

**Comment by dchiu911** [comment]
I got the same issue after updating to 0.5.0 but solved it by running
```r
packrat::set_opts(symlink.system.packages = TRUE)
```
It seems that `packrat/packrat.opts` didn't get automatically updated with the new option.

**Comment by kevinushey** [comment]
Doh. Thanks for the explanation; I understand what's going on now. I'll try to get this fixed. In the meantime @dchiu911's solution should work for 'migrating' old Packrat projects to the latest version.

**Comment by kevinushey** [comment]
Should hopefully be fixed in the development version of Packrat with https://github.com/rstudio/packrat/commit/da40b6e553ce397216472c13d8a6bbb360682149.

**Comment by nacnudus** [comment]
I came here via #524. Installing the development version didn't fix it it for me, but running `packrat::set_opts(symlink.system.packages = TRUE)` did.

**Comment by kevinushey** [comment]
Sorry again for the trouble. I've pushed another commit that should (hopefully) resolve this.

**Comment by nacnudus** [comment]
Thanks, it works now.
