### ISSUE TITLE
Implement a dependency-free install_github

### ISSUE THREAD

**Issue by kevinushey** [rstudio/packrat#65]
The tricky bits:
1. Handling authentication (for installing from private repos),
2. Handling pull requests (need to communicate with GitHub API to map pull request numbers to refs),
3. ...without any package dependencies.

We might be able to use some command line tools here; ie, even if we can't use `RCurl` we can maybe still use `curl`.

**Comment by cderv** [comment]
I think `remotes::install_github` is the dependency free install_github that was wished a few years ago.  
``` r
tools::package_dependencies("remotes", recursive = TRUE)
#> $remotes
#> [1] "methods" "utils"
```

**Comment by dchiu911** [comment]
Hi @kevinushey 

I tried to snapshot a public GitHub package, but it failed with the previously observed error:

```
Error in snapshotSources(project, activeRepos(project), allRecordsFlat) : 
  Errors occurred when fetching source files:
Error in getSourceForPkgRecord(pkgRecord, sourceDir, availablePkgs, repos) : 
  Failed to download package from URL:
- "api.github.com/repos/AlineTalhouk/splendid/tarball/2ef9cc638dfec19a9e0bc4693c1e9d0affc332f2"
```
I found some help at https://github.com/rstudio/packrat/issues/447#issuecomment-360739671 (even though that was for a private repo). The snapshot worked after I installed `devtools`, even though I already had `remotes` installed. Perhaps the condition [here](https://github.com/rstudio/packrat/blob/master/R/github.R#L6) should be relaxed/modified to use `remotes` to reduce the number of dependencies one needs.

**Comment by kevinushey** [comment]
What version of Packrat are you using? It seems strange that there is no `https://` prefixed on that URL.

IIUC this should've been fixed in the development version of Packrat: https://github.com/rstudio/packrat/commit/f3c7e0d79169301da119a27bf12356f6ac94fe14

**Comment by dchiu911** [comment]
Thanks, I am using the CRAN release 0.5.0, will let you know if the devel doesn't resolve.
